menu:
# - {name: 'people', url: '/people'}
- {name: 'Publications', url: '/publications'}
- {name: 'Conferences', url: '/conferences'}
- {name: 'Projects', url: '/projects'}
# - {name: 'courses', url: '/courses'}
- {name: 'Curriculum Vitae', url: '/cv'}
- {name: 'Contact', url: '/contact'}

# people:
# - {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

# courses:
# - {name: 'Vector Calculus', url: 'vector-calculus'}
# - {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
# - {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/MunQ-Lee'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=AKOUtfoAAAAJ'}
# - {icon: 'facebook', link: 'https://www.facebook.com/munkyu94'}
- {icon: 'instagram', link: 'https://www.instagram.com/munkyu94'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/munq-lee'}

contacts:
- {name: 'Munkyu Lee', title: 'Ph.D. student', department: 'Electrical & Electronics Engineering | Major: Computer', institution: 'Chung-Ang University', institution_address: '84, Heukseok-ro, Dongjak-gu, Seoul, Republic of Korea', phone: '+82 10-7199-9765', email: 'dse112@cau.ac.kr', office: '209-309', image: 'assets/img/contact.jpg'}
